console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints
console.log(Math.floor(Math.random() * 100) + 1);  // 1 to 100 random numbers are prints